stages:
  - test
  - run
  - deploy

variables:
  serversshuser: 'ssh-w019308c'
  servername: 'laengstes.serverless.industries'
  wwwdir: '/www/htdocs/w019308c/vhosts/laengstes.serverless.industries'


#
# -> Template
#

.tpl:default:
  image: reg.git.brickburg.de/bbcontainers/hub/debian:latest
  only:
    - schedules
    - web
  tags:
    - docker

.tpl:dotnet:
  image: reg.git.brickburg.de/bbcontainers/dotnetcore:dotnet6-sdk
  extends: .tpl:default

.tpl:deploy:
  extends: .tpl:default
  image: reg.git.brickburg.de/bbcontainers/hyde:current
  before_script:
    - 'mkdir ssh'
    - 'touch ssh/hosts ssh/key'
    - 'chmod u=rwx,go=- ssh'
    - 'chmod u=rw,go=- ssh/hosts ssh/key'
    - 'echo "${SSH_DEPLOY_KEY}" > ssh/key'
    - 'ssh-keyscan -H ${servername} > ssh/hosts'
  after_script:
    - 'rm -rf ssh'
  variables:
    sshopts: '-o UserKnownHostsFile=ssh/hosts -i ssh/key'
    sshremote: '${serversshuser}@${servername}'


#
# -> Jobs
#

test:parser:
  extends: .tpl:dotnet
  stage: test
  script:
    - 'cd ParserTest'
    - 'dotnet test'

run:buildandrun:
  extends: .tpl:dotnet
  stage: run
  script:
    - 'mkdir dist'
    - 'dotnet publish --no-self-contained -c Debug -r linux-x64 -o dist ForumParser/ForumParser.csproj'
    - 'mkdir result'
    - 'COMPlus_DebugWriteToStdErr=1 ./dist/ForumParser https://forum.netcup.de/sonstiges/smalltalk/1051-das-l%C3%A4ngste-thema/ ./result/laengstes.json ./result/laengstes.html'
  artifacts:
    name: '$CI_JOB_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - 'result'

deploy:laengstes:
  extends: .tpl:deploy
  stage: deploy
  environment:
    name: Live
    url: "https://laengstes.serverless.industries/"
  script:
    - 'ssh ${sshopts} ${sshremote} "rm -rf ${wwwdir}/*"'
    - 'scp -r ${sshopts} result/laengstes.html ${sshremote}:${wwwdir}/index.html'
